# Generated by Django 4.1 on 2022-08-24 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hermano',
            old_name='documento',
            new_name='documento2',
        ),
        migrations.RenameField(
            model_name='hermano',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento2',
        ),
        migrations.RenameField(
            model_name='hermano',
            old_name='nombre',
            new_name='nombre2',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='documento',
            new_name='documento1',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='fecha_nacimiento',
            new_name='fecha_nacimiento1',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='nombre',
            new_name='nombre1',
        ),
    ]
